title: Default Page

tabs:
  content:
    icon: text
    label: Content
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              text:
                type: blocks
      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files
  meta: tabs/meta/page
