title: Project

columns:
  - width: 2/3
    label: Content
    sections:
      content:
        type: fields
        fields:
          subtitle:
            label: Sous-titre
            type: text
          content:
            label: Contenu
            type: textarea

  - width: 1/3
    label: Meta
    sections:
      meta:
        type: fields
        fields:
          author:
            type: users
            max: 1
          date:
            type: date
            time: true
            default: now
