title: Site

options:
  create: false

tabs:
  content:
    icon: text
    label: Content
    sections:
      pages:
        type: pages
        image:
          query: page.images.first ?? page.children.first.images.first
          cover: true
  meta: tabs/meta/site
